name:                knowit2021
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/knowit2021#readme
license:             BSD3
author:              Author name here
maintainer:          example@example.com
copyright:           2021 Author name here
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - gps
  - split
  - containers
  - extra
  - lens
  - linear
  - parsec
  - multiset

executables:
  knowit2021:
    source-dirs:      src
    main:             Main.hs
